# ── Nginx Access Log ─────────────────────────────────────────
[monitor:///var/log/nginx/access.log]
disabled = false
index    = corptech
sourcetype = nginx_access
host     = corptech_nginx

[monitor:///var/log/nginx/error.log]
disabled = false
index    = corptech
sourcetype = nginx_error
host     = corptech_nginx

# ── Syslog UDP (for future pfSense / Linux VMs) ──────────────
[udp://5514]
disabled    = false
index       = corptech
sourcetype  = syslog
connection_host = dns
