#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Helpdesk Task 1 — Reset an AD user's password.
    Generates a secure temporary password and forces change at next logon.

.PARAMETER Username
    The SAM account name of the user (e.g. djohnson)

.PARAMETER TicketNumber
    The osTicket number this action is associated with (e.g. 100001)

.PARAMETER Password
    Optional: specify the temp password instead of auto-generating one.
    If omitted, a secure random password is generated.

.PARAMETER NoForceChange
    If set, the user will NOT be required to change their password at next logon.
    Default is to always force a change (best practice).

.EXAMPLE
    .\01-reset-password.ps1 -Username djohnson -TicketNumber 100001

.EXAMPLE
    .\01-reset-password.ps1 -Username kthompson -TicketNumber 100002 -Password "Welc0me!Temp99"
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory)]
    [string]$Username,

    [string]$TicketNumber = "",

    [string]$Password = "",

    [switch]$NoForceChange
)

. "$PSScriptRoot\00-helpdesk-common.ps1"
Assert-ADModule

$script:TicketNumber = $TicketNumber

Write-Banner -Title "Password Reset" -Ticket $TicketNumber

# ── Step 1: Look up user ──────────────────────────────────────
Write-HDLog "Looking up user: $Username"
$user = Get-ValidatedADUser -Username $Username
if (-not $user) { exit 1 }

Show-UserSummary -User $user

if (-not $user.Enabled) {
    Write-HDLog "Account is DISABLED. Cannot reset password on a disabled account." "WARN"
    Write-Host "  Use 04-offboard-user.ps1 to manage disabled accounts." -ForegroundColor Yellow
    if (-not (Confirm-Action "Reset anyway? (unusual — confirm with your team lead)")) { exit 0 }
}

# ── Step 2: Determine new password ───────────────────────────
$isAutoGenerated = $false
if ($Password -eq "") {
    $Password = New-TempPassword
    $isAutoGenerated = $true
    Write-HDLog "Generated temporary password automatically"
} else {
    Write-HDLog "Using provided password"
}

$securePass = ConvertTo-SecureString $Password -AsPlainText -Force

# ── Step 3: Confirm before acting ────────────────────────────
Write-Host "  About to reset password for: " -NoNewline
Write-Host $user.Name -ForegroundColor Yellow
Write-Host "  Force change at next logon : " -NoNewline
Write-Host $(if (-not $NoForceChange) { "YES (recommended)" } else { "No" }) -ForegroundColor $(if (-not $NoForceChange) { "Green" } else { "Yellow" })
Write-Host ""

if (-not (Confirm-Action "Proceed with password reset?")) {
    Write-HDLog "Password reset cancelled by agent." "WARN"
    exit 0
}

# ── Step 4: Reset the password ───────────────────────────────
try {
    if ($PSCmdlet.ShouldProcess($user.SamAccountName, "Reset-ADAccountPassword")) {
        Set-ADAccountPassword -Identity $user.SamAccountName `
            -NewPassword $securePass -Reset -ErrorAction Stop
        Write-HDLog "Password reset successfully for $($user.SamAccountName)" "OK"
    }
} catch {
    Write-HDLog "Password reset FAILED: $($_.Exception.Message)" "ERROR"
    Write-HDLog "Common causes: password does not meet complexity/length requirements" "WARN"
    exit 1
}

# ── Step 5: Force change at next logon ───────────────────────
if (-not $NoForceChange) {
    try {
        Set-ADUser -Identity $user.SamAccountName `
            -ChangePasswordAtLogon $true -ErrorAction Stop
        Write-HDLog "ChangePasswordAtLogon set to TRUE" "OK"
    } catch {
        Write-HDLog "Could not set ChangePasswordAtLogon: $($_.Exception.Message)" "WARN"
    }
}

# ── Step 6: If account was locked, unlock it too ─────────────
if ($user.LockedOut) {
    try {
        Unlock-ADAccount -Identity $user.SamAccountName -ErrorAction Stop
        Write-HDLog "Account was locked — also unlocked as part of reset" "OK"
    } catch {
        Write-HDLog "Could not unlock account: $($_.Exception.Message)" "WARN"
    }
}

# ── Step 7: Log the action ────────────────────────────────────
Write-HDLog "ACTION: Password reset | User=$($user.SamAccountName) | Dept=$($user.Department) | Auto-generated=$isAutoGenerated | ForceChange=$(-not $NoForceChange)" "ACTION"

# ── Step 8: Output the result ────────────────────────────────
Write-Host ""
Write-Host "  ── Reset Complete ───────────────────────────" -ForegroundColor DarkCyan
Write-Result "User"              $user.Name              "Green"
Write-Result "Username"          $user.SamAccountName    "Green"
Write-Result "Temp Password"     $Password               "Yellow"
Write-Result "Force PW Change"   $(if (-not $NoForceChange) {"Yes"} else {"No"})
Write-Result "Log Written To"    $script:LogFile         "DarkGray"
Write-Host ""
Write-Host "  !! Copy the temp password BEFORE closing this window !!" -ForegroundColor Yellow
Write-Host "  !! Do not send passwords via email — use phone or in-person !!" -ForegroundColor Yellow
Write-Host ""

# Clipboard copy (Windows only, non-fatal if it fails)
try {
    $Password | Set-Clipboard
    Write-Host "  [Temp password copied to clipboard]" -ForegroundColor DarkGray
} catch { }

Write-Host ""
Write-Host "  Next steps for the user:" -ForegroundColor DarkGray
Write-Host "    1. Log in with the temp password above" -ForegroundColor DarkGray
Write-Host "    2. Windows will immediately prompt for a new password" -ForegroundColor DarkGray
Write-Host "    3. New password must be 14+ chars and meet complexity rules" -ForegroundColor DarkGray
Write-Host ""
